### ISSUE TITLE
I'd like to mention one bugger

### ISSUE THREAD

**Issue by focusnews** [xyxyLiu/SwipeRefreshLayout#3]
<?xml version="1.0" encoding="utf-8"?>
<dev.xesam.chelaile.app.widget.pulltorefresh.CustomSwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:swiperefresh="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipelayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/windowBackground"
    swiperefresh:enable_top_progress_bar="true"
    swiperefresh:keep_refresh_head="true"
    swiperefresh:refresh_mode="pull_mode"
    swiperefresh:time_out_refresh_complete="200"
    swiperefresh:time_out_return_to_top="500">

```
<FrameLayout
    android:id="@+id/content_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:touchscreenBlocksFocus="false">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/cll_act_favorite_type_lines"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        style="@style/V4.RefreshList" />

    <View
        android:id="@+id/none_data"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

</FrameLayout>
```

</dev.xesam.chelaile.app.widget.pulltorefresh.CustomSwipeRefreshLayout>

This leads to sliding conflicts

**Comment by xyxyLiu** [comment]
fixed in 1.1.0
