### ISSUE TITLE
Touch event doesn't works fine

### ISSUE THREAD

**Issue by maddenbrain** [xyxyLiu/SwipeRefreshLayout#4]
Child touches works bad. I think, something wrong with touch slop.
How to reproduce: create customSwipeRefreshLayout with ExpandableListView in it.

**Comment by maddenbrain** [comment]
Found solution: you must add
if(!mCheckValidMotionFlag) {
  updatePositionTimeout(false);
  handled = true;
}
at 964 str. This will fix the problem.

**Comment by xyxyLiu** [comment]
You're right.  It's a bug in child touch. I have fixed that in onInterceptTouchEvent(). Thanks!
