### ISSUE TITLE
how can i use different language

### ISSUE THREAD

**Issue by hasan5151** [xyxyLiu/SwipeRefreshLayout#7]
How can i use different language?
"Swipe to refresh"
"Release to refresh"
"Refreshing complete"

**Comment by xyxyLiu** [comment]
Unfortunately, the text in the default head view provided in the library can not be modified currently. You'd better create your own refresh head layout (see [create-custom-head-refresh-view](https://github.com/xyxyLiu/SwipeRefreshLayout#create-custom-head-refresh-view-optional)) to support different languages.
